### ISSUE TITLE
question about the some results in paper

### ISSUE THREAD

**Issue by beautifulchoi** [waczjoan/gaussian-mesh-splatting#1]
Hello, 
first of all thank you for your great work! it's very interesting that simple idea can effect a lot.

but I wonder about trial you did. as you mentioned in limitation, there is insufficient explanation about number of gaussian per faces. 
so, did you also try to make each splitting parameter of face and number of gaussian trainable for adapting?  

also, in main repo page, it seems that there is some artifact like sauce is also painted under plate in flying hotdog gif. is it also limitation of large mesh face?

**Comment by waczjoan** [comment]
Hello,
Thank you very much for your words of appreciation! 

1) actually selecting the number of Gaussians is a non-trivial task; What you are proposing -- varying the number of Gaussians per face during training, is less trivial to implement at this point; we have thought of several solutions, such as splitting large faces into smaller ones during training. However, we were thinking about it more like Future work/development model. Instead, we focused on scenarios when we don't have a mesh and create a pseudo-mesh. Then this problem does not occur -- we use pruning, such as in the original GS. If you have any ideas we would love to hear about them, we are very open.

2.) "It seems that there is some artifact like sauce is also painted under plate in flying hotdog gif."

Well. It's "Not a Bug, It's a Feature." :)

If you think about it, it's not an artifact. There was never a view of the plate from below during training (in the training dataset), so we don't know how it looks there. Since Gaussians are "double-sided" -- looking at it from the other side will also give a certain render. In the paper we mentioned the use of this fact in the Appendix (see, Fig 16c): "Note that Gaussians represent color from two sides. Therefore, after removing the soil from the pot, we can still see the inner side of the pot"
