### ISSUE TITLE
About GaMeS Gaussian Modification

### ISSUE THREAD

**Issue by willyawan16** [waczjoan/gaussian-mesh-splatting#24]
GaMeS is really an interesting method of editable gaussian splatting, but i want to ask..

**Does the gaussian modification can only be implemented by writing a python script?**
In your paper, it stated that we can modify the gaussian in similar way of modifying a mesh. And it seems that we could scale, bend and even ignoring certain parts. So, does this modification can **ONLY** be implemented by script?

And also, what does it mean by "In fact, modification depends only on user skills." in page 11 of your paper?

**Comment by waczjoan** [comment]
Thank you for your interest in our project!

We appreciate your question, as it highlights an area where many users have experienced some confusion regarding modifications. One user pointed out that "pseudomesh" is also known as "triangle soup," which is why we have transitioned to using this alternative name in our documentation.

To clarify: modifications to the pseudomesh/triangle soup can be performed using external tools like Blender. These modifications are done manually and allow for a wide range of transformations, as long as they are reasonable within the tool's capabilities. At this time, we do not plan to develop a dedicated external editing tool due to limited team resources.

In summary: pseudomesh/triangle soup can be modified (within practical limits) without script, using tools like Blender. 
Modifying a mesh or pseudomesh using an external tool like Blender requires not only familiarity with the tool itself but also a degree of artistic skill from the user. This is what we mean by the phrase, "In fact, modification depends only on user skills.”

We encourage you to check the updated version of our article, where we have refined the explanation. 

- https://arxiv.org/abs/2402.01459 (See Fig. 1, 2)

Additionally, we have included a section about modifications in the README for further reference:

https://github.com/waczjoan/gaussian-mesh-splatting?tab=readme-ov-file#pseudomeshtriangle-soup-and-modifications

Let us know if you have further questions.
